In [2]:
import numpy as np
import pandas as pd
from datetime import *

# 1. Find the least amount sale that was done for each item.

In [3]:
sd=pd.read_excel('SaleData.xlsx')
print(sd.groupby(['Item'])['Sale_amt'].min())

Item
Cell Phone      3375.0
Desk             250.0
Home Theater    2000.0
Television      8386.0
Video Games      936.0
Name: Sale_amt, dtype: float64

# 2. Compute the total sales for each year and region across all items

In [4]:
# total sales of each year and region grouped
print(sd.groupby([sd.OrderDate.dt.year,sd.Region])['Sale_amt'].sum())

OrderDate  Region
2018       Central    479825.0
           East       293780.0
           West       105424.0
2019       Central    349944.5
           East        27227.0
           West        49475.0
Name: Sale_amt, dtype: float64

In [5]:
uniqueYears = sd['OrderDate'].dt.year.unique()
uniqueRegions = sd['Region'].unique()
uniqueRegions

array(['East', 'Central', 'West'], dtype=object)

In [7]:
# Total sales of each year
pd.DataFrame(sd.groupby([sd.OrderDate.dt.year])["Sale_amt"].sum())

           Sale_amt
OrderDate
2018       879029.0
2019       426646.5

In [8]:
#total sales of each month
pd.DataFrame(sd.groupby(sd.Region)['Sale_amt'].sum())

         Sale_amt
Region
Central  829769.5
East     321007.0
West     154899.0

# 3. Create new column 'days_diff' with number of days difference between a reference date passed and each order date

In [33]:
date2=date.today()
cnt=sd['OrderDate'].count()
sd.insert(8,'days_diff','nan')
for i in range(cnt):
    date1=str(sd.iat[i,0]).split(" ")[0]
    sd.iat[i,8]=(date2-datetime.strptime(date1, "%Y-%m-%d").date()).days
sd

#present date is taken as reference date

,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt,days_diff
0,2018-01-06,East,Martha,Alexander,Television,95,1198.0,113810.0,805
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50,500.0,25000.0,788
2,2018-02-09,Central,Hermann,Luis,Television,36,1198.0,43128.0,771
3,2018-02-26,Central,Timothy,David,Cell Phone,27,225.0,6075.0,754
4,2018-03-15,West,Timothy,Stephen,Television,56,1198.0,67088.0,737
5,2018-04-01,East,Martha,Alexander,Home Theater,60,500.0,30000.0,720
6,2018-04-18,Central,Martha,Steven,Television,75,1198.0,89850.0,703
7,2018-05-05,Central,Hermann,Luis,Television,90,1198.0,107820.0,686
8,2018-05-22,West,Douglas,Michael,Television,32,1198.0,38336.0,669
9,2018-06-08,East,Martha,Alexander,Home Theater,60,500.0,30000.0,652
10,2018-06-25,Central,Hermann,Sigal,Television,90,1198.0,107820.0,635
11,2018-07-12,East,Martha,Diana,Home Theater,29,500.0,14500.0,618
12,2018-07-29,East,Douglas,Karen,Home Theater,81,500.0,40500.0,601
13,2018-08-15,East,Martha,Alexander,Television,35,1198.0,41930.0,584
14,2018-09-01,Central,Douglas,John,Desk,2,125.0,250.0,567
15,2018-09-18,East,Martha,Alexander,Video Games,16,58.5,936.0,550
16,2018-10-05,Central,Hermann,Sigal,Home Theater,28,500.0,14000.0,533
17,2018-10-22,East,Martha,Alexander,Cell Phone,64,225.0,14400.0,516
18,2018-11-08,East,Douglas,Karen,Cell Phone,15,225.0,3375.0,499
19,2018-11-25,Central,Hermann,Shelli,Video Games,96,58.5,5616.0,482
20,2018-12-12,Central,Douglas,John,Television,67,1198.0,80266.0,465
21,2018-12-29,East,Douglas,Karen,Video Games,74,58.5,4329.0,448
22,2019-01-15,Central,Timothy,David,Home Theater,46,500.0,23000.0,431
23,2019-02-01,Central,Douglas,John,Home Theater,87,500.0,43500.0,414
24,2019-02-18,East,Martha,Alexander,Home Theater,4,500.0,2000.0,397
25,2019-03-07,West,Timothy,Stephen,Home Theater,7,500.0,3500.0,380
26,2019-03-24,Central,Hermann,Luis,Video Games,50,58.5,2925.0,363
27,2019-04-10,Central,Martha,Steven,Television,66,1198.0,79068.0,346
28,2019-04-27,East,Martha,Diana,Cell Phone,96,225.0,21600.0,329
29,2019-05-14,Central,Timothy,David,Television,53,1198.0,63494.0,312
30,2019-05-31,Central,Timothy,David,Home Theater,80,500.0,40000.0,295
31,2019-06-17,Central,Hermann,Shelli,Desk,5,125.0,625.0,278
32,2019-07-04,East,Martha,Alexander,Video Games,62,58.5,3627.0,261
33,2019-07-21,Central,Hermann,Sigal,Video Games,55,58.5,3217.5,244
34,2019-08-07,Central,Hermann,Shelli,Video Games,42,58.5,2457.0,227
35,2019-08-24,West,Timothy,Stephen,Desk,3,125.0,375.0,210
36,2019-09-10,Central,Timothy,David,Television,7,1198.0,8386.0,193
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76,225.0,17100.0,176
38,2019-10-14,West,Douglas,Michael,Home Theater,57,500.0,28500.0,159
39,2019-10-31,Central,Martha,Steven,Television,14,1198.0,16772.0,142
40,2019-11-17,Central,Hermann,Luis,Home Theater,11,500.0,5500.0,125
41,2019-12-04,Central,Hermann,Luis,Home Theater,94,500.0,47000.0,108
42,2019-12-21,Central,Martha,Steven,Home Theater,28,500.0,14000.0,91

# 4. Create a dataframe with two columns: 'manager', 'list_of_salesmen'. Column 'manager' will contain the unique managers present and column 'list_of_salesmen' will contain an array of all salesmen under each manager

In [9]:
pd.DataFrame(sd.groupby(sd.Manager)['SalesMan'].unique()).rename(columns={'SalesMan':"list_of_salesmen"})

                   list_of_salesmen
Manager
Douglas      [Michael, Karen, John]
Hermann       [Shelli, Luis, Sigal]
Martha   [Alexander, Steven, Diana]
Timothy            [David, Stephen]

# 5. For all regions find number of salesman and total sales. Return as a dataframe with three columns - Region, salesmen_count and total_sales

In [34]:
regional_sales=pd.DataFrame(columns=['Region','salesmen_count','total_sales'])
for region in sd['Region'].unique():
    salesmen_cnt=sd[sd['Region']==region]['SalesMan'].unique().size
    sales_sum=sd[sd['Region']==region]['Sale_amt'].sum()
    regional_sales=regional_sales.append({'Region':region,'salesmen_count':salesmen_cnt,'total_sales':sales_sum},ignore_index=True)
regional_sales

    Region salesmen_count  total_sales
0     East              3     321007.0
1  Central              6     829769.5
2     West              2     154899.0

# 6. Create a dataframe with total sales as percentage for each manager. Dataframe to contain manager and percent_sales

In [10]:
manager_sales=pd.DataFrame(columns=['manager','percent_sales'])
total_sales=sd['Sale_amt'].sum()
for manager in sd['Manager'].unique():
    sales=sd[manager==sd['Manager']]['Sale_amt'].sum()
    percent=(sales/total_sales)*100
    manager_sales=manager_sales.append({'manager':manager,'percent_sales':percent},ignore_index=True)
manager_sales

   manager  percent_sales
0   Martha      36.187629
1  Hermann      27.963188
2  Timothy      17.540193
3  Douglas      18.308990

In [11]:
df2=pd.read_csv('diamonds.csv')

# 7. Count the duplicate rows of diamonds dataframe.

In [12]:
len(df2[df2.duplicated()].index)

149

# 8. Drop rows in case of missing values in carat and cut columns.

In [13]:
df2.dropna(subset=['carat','cut'])

       carat        cut color clarity  depth  table   price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0   326.0  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0   326.0  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0   327.0  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0   334.0  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0   335.0  4.34  4.35  2.75
5       0.24  Very Good     J    VVS2   62.8   57.0     NaN  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0   336.0  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0   337.0  4.07  4.11  2.53
8       0.22       Fair     E     VS2   65.1   61.0   337.0  3.87  3.78  2.49
9       0.23  Very Good     H     VS1   59.4   61.0   338.0  4.00  4.05  2.39
10      0.31       Good     J     SI2   63.3   58.0   335.0  4.34  4.35  2.75
11       0.3       Good     J     SI1   64.0   55.0   339.0  4.25  4.28  2.73
12      0.23      Ideal     J     VS1   62.8   56.0   340.0  3.93  3.90  2.46
13      0.22    Premium     F     SI1   60.4   61.0   342.0  3.88  3.84  2.33
14      0.31      Ideal     J     SI2   62.2   54.0   344.0  4.35  4.37  2.71
15     '0.2'    Premium     E     SI2   60.2   62.0   345.0  3.79  3.75  2.27
16      0.32    Premium     E      I1   60.9   58.0   345.0  4.38  4.42  2.68
17       0.3      Ideal     I     SI2   62.0   54.0   348.0  4.31  4.34  2.68
18       0.3       Good     J     SI1   63.4   54.0   351.0  4.23  4.29   2.7
19       0.3       Good     J     SI1   63.8   56.0   351.0  4.23  4.26   NaN
20       0.3  Very Good     J     SI1   62.7   59.0   351.0  4.21  4.27  2.66
21       0.3       Good     I     SI2   63.3   56.0   351.0  4.26  4.30  None
22      0.23  Very Good     E     VS2   63.8   55.0   352.0  3.85  3.92  2.48
23      0.23  Very Good     H     VS1   61.0   57.0   353.0  3.94  3.96  2.41
24      0.31  Very Good     J     SI1   59.4   62.0   353.0  4.39  4.43  2.62
25       0.3       Good     J     SI1   63.4   54.0   351.0  4.23  4.29   2.7
26      0.31  Very Good     J     SI1   58.1   62.0   353.0  4.44  4.47  2.59
27      0.23  Very Good     G    VVS2   60.4   58.0   354.0  3.97  4.01  2.41
28      0.24    Premium     I     VS1   62.5   57.0   355.0  3.97  3.94  2.47
29       0.3  Very Good     J     VS2   62.2   57.0   357.0  4.28  4.30  2.67
...      ...        ...   ...     ...    ...    ...     ...   ...   ...   ...
53913   0.57    Premium     E      IF   59.8   60.0  2753.0  5.43  5.38  3.23
53914   0.61    Premium     F    VVS1   61.8   59.0  2753.0  5.48  5.40  3.36
53915    0.8       Good     G     VS2   64.2   58.0  2753.0  5.84  5.81  3.74
53916   0.84       Good     I     VS1   63.7   59.0  2753.0  5.94  5.90  3.77
53917   0.77      Ideal     E     SI2   62.1   56.0  2753.0  5.84  5.86  3.63
53918   0.74       Good     D     SI1   63.1   59.0  2753.0  5.71  5.74  3.61
53919    0.9  Very Good     J     SI1   63.2   60.0  2753.0  6.12  6.09  3.86
53920   0.76    Premium     I     VS1   59.3   62.0  2753.0  5.93  5.85  3.49
53921   0.76      Ideal     I    VVS1   62.2   55.0  2753.0  5.89  5.87  3.66
53922    0.7  Very Good     E     VS2   62.4   60.0  2755.0  5.57  5.61  3.49
53923    0.7  Very Good     E     VS2   62.8   60.0  2755.0  5.59  5.65  3.53
53924    0.7  Very Good     D     VS1   63.1   59.0  2755.0  5.67  5.58  3.55
53925   0.73      Ideal     I     VS2   61.3   56.0  2756.0  5.80  5.84  3.57
53926   0.73      Ideal     I     VS2   61.6   55.0  2756.0  5.82  5.84  3.59
53927   0.79      Ideal     I     SI1   61.6   56.0  2756.0  5.95  5.97  3.67
53928   0.71      Ideal     E     SI1   61.9   56.0  2756.0  5.71  5.73  3.54
53929   0.79       Good     F     SI1   58.1   59.0  2756.0  6.06  6.13  3.54
53930   0.79    Premium     E     SI2   61.4   58.0  2756.0  6.03  5.96  3.68
53931   0.71      Ideal     G     VS1   61.4   56.0  2756.0  5.76  5.73  3.53
53932   0.71    Premium     E     SI1   60.5   55.0  2756.0  5.79  5.74  3.49
53933   0.71    Premium     F     SI1   59.8   62.0  2756.0  5.74  5.73  3.43
53934    0.7  Very Good     E     VS2   60.5   59.0  2757.0  5.71  5.76  3.47
53935   0.71    Premium     E     SI1   60.5   55.0  2756.0  5.79  5.74  3.49
53936    0.7  Very Good     E     VS2   61.2   59.0  2757.0  5.69  5.72  3.49
53937   0.72    Premium     D     SI1   62.7   59.0  2757.0  5.69  5.73  3.58
53938   0.72      Ideal     D     SI1   60.8   57.0  2757.0  5.75  5.76   3.5
53939   0.72       Good     D     SI1   63.1   55.0  2757.0  5.69  5.75  3.61
53940    0.7  Very Good     D     SI1   62.8   60.0  2757.0  5.66  5.68  3.56
53941   0.86    Premium     H     SI2   61.0   58.0  2757.0  6.15  6.12  3.74
53942   0.75      Ideal     D     SI2   62.2   55.0  2757.0  5.83  5.87  3.64

[53941 rows x 10 columns]

# 9. Subset the dataframe with only numeric columns.

In [14]:
df2._get_numeric_data()

       depth  table   price     x     y
0       61.5   55.0   326.0  3.95  3.98
1       59.8   61.0   326.0  3.89  3.84
2       56.9   65.0   327.0  4.05  4.07
3       62.4   58.0   334.0  4.20  4.23
4       63.3   58.0   335.0  4.34  4.35
5       62.8   57.0     NaN  3.94  3.96
6       62.3   57.0   336.0  3.95  3.98
7       61.9   55.0   337.0  4.07  4.11
8       65.1   61.0   337.0  3.87  3.78
9       59.4   61.0   338.0  4.00  4.05
10      63.3   58.0   335.0  4.34  4.35
11      64.0   55.0   339.0  4.25  4.28
12      62.8   56.0   340.0  3.93  3.90
13      60.4   61.0   342.0  3.88  3.84
14      62.2   54.0   344.0  4.35  4.37
15      60.2   62.0   345.0  3.79  3.75
16      60.9   58.0   345.0  4.38  4.42
17      62.0   54.0   348.0  4.31  4.34
18      63.4   54.0   351.0  4.23  4.29
19      63.8   56.0   351.0  4.23  4.26
20      62.7   59.0   351.0  4.21  4.27
21      63.3   56.0   351.0  4.26  4.30
22      63.8   55.0   352.0  3.85  3.92
23      61.0   57.0   353.0  3.94  3.96
24      59.4   62.0   353.0  4.39  4.43
25      63.4   54.0   351.0  4.23  4.29
26      58.1   62.0   353.0  4.44  4.47
27      60.4   58.0   354.0  3.97  4.01
28      62.5   57.0   355.0  3.97  3.94
29      62.2   57.0   357.0  4.28  4.30
...      ...    ...     ...   ...   ...
53913   59.8   60.0  2753.0  5.43  5.38
53914   61.8   59.0  2753.0  5.48  5.40
53915   64.2   58.0  2753.0  5.84  5.81
53916   63.7   59.0  2753.0  5.94  5.90
53917   62.1   56.0  2753.0  5.84  5.86
53918   63.1   59.0  2753.0  5.71  5.74
53919   63.2   60.0  2753.0  6.12  6.09
53920   59.3   62.0  2753.0  5.93  5.85
53921   62.2   55.0  2753.0  5.89  5.87
53922   62.4   60.0  2755.0  5.57  5.61
53923   62.8   60.0  2755.0  5.59  5.65
53924   63.1   59.0  2755.0  5.67  5.58
53925   61.3   56.0  2756.0  5.80  5.84
53926   61.6   55.0  2756.0  5.82  5.84
53927   61.6   56.0  2756.0  5.95  5.97
53928   61.9   56.0  2756.0  5.71  5.73
53929   58.1   59.0  2756.0  6.06  6.13
53930   61.4   58.0  2756.0  6.03  5.96
53931   61.4   56.0  2756.0  5.76  5.73
53932   60.5   55.0  2756.0  5.79  5.74
53933   59.8   62.0  2756.0  5.74  5.73
53934   60.5   59.0  2757.0  5.71  5.76
53935   60.5   55.0  2756.0  5.79  5.74
53936   61.2   59.0  2757.0  5.69  5.72
53937   62.7   59.0  2757.0  5.69  5.73
53938   60.8   57.0  2757.0  5.75  5.76
53939   63.1   55.0  2757.0  5.69  5.75
53940   62.8   60.0  2757.0  5.66  5.68
53941   61.0   58.0  2757.0  6.15  6.12
53942   62.2   55.0  2757.0  5.83  5.87

[53943 rows x 5 columns]

# 10. Compute volume as (x*y*z) when depth is greater than 60. In case of depth less than 60 default volume to 8.

In [15]:
# 'z' column has both Nan and 'None', that has to be replace by the mean , 
cleanDataofZ =df2[(~df2['z'].isna())&(df2['z'] != 'None')]
meanZ = cleanDataofZ['z'].astype('float').mean() #mean of 'z' column is calculated

In [16]:
df2.loc[(df2['z'].isna())|(df2['z'] == 'None'),'z']=meanZ  # 'None' and Nan are replaced by its mean for column 'z'

In [17]:
def vol(depth,x,y,z):
    if depth>60 :
        return x*y*float(z)
    else:
        return  8
volume = df2.apply(lambda row : vol(row['depth'],row['x'],row['y'],row['z']),axis=1)
vol= pd.DataFrame(volume,columns=['Volume'])
df2['volume'] = vol
df2.head(20)

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326.0,3.89,3.84,2.31,8.000000
2,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31,8.000000
3,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,51.917250
5,0.24,Very Good,J,VVS2,62.8,57.0,NaN,3.94,3.96,2.48,38.693952
6,0.24,Very Good,I,VVS1,62.3,57.0,336.0,3.95,3.98,2.47,38.830870
7,0.26,Very Good,H,SI1,61.9,55.0,337.0,4.07,4.11,2.53,42.321081
8,0.22,Fair,E,VS2,65.1,61.0,337.0,3.87,3.78,2.49,36.425214
9,0.23,Very Good,H,VS1,59.4,61.0,338.0,4.00,4.05,2.39,8.000000
10,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,51.917250
11,0.3,Good,J,SI1,64.0,55.0,339.0,4.25,4.28,2.73,49.658700
12,0.23,Ideal,J,VS1,62.8,56.0,340.0,3.93,3.90,2.46,37.704420
13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.88,3.84,2.33,34.715136
14,0.31,Ideal,J,SI2,62.2,54.0,344.0,4.35,4.37,2.71,51.515745
15,'0.2',Premium,E,SI2,60.2,62.0,345.0,3.79,3.75,2.27,32.262375
16,0.32,Premium,E,I1,60.9,58.0,345.0,4.38,4.42,2.68,51.883728
17,0.3,Ideal,I,SI2,62.0,54.0,348.0,4.31,4.34,2.68,50.130472
18,0.3,Good,J,SI1,63.4,54.0,351.0,4.23,4.29,2.7,48.996090
19,0.3,Good,J,SI1,63.8,56.0,351.0,4.23,4.26,3.53877,63.767912

# 11. Impute missing price values with mean

In [18]:
mean=df2['price'].mean()
d={'price':mean}
pd.set_option('precision',1)
df2.fillna(d)

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326.0,4.0,4.0,2.43,38.2
1,0.21,Premium,E,SI1,59.8,61.0,326.0,3.9,3.8,2.31,8.0
2,0.23,Good,E,VS1,56.9,65.0,327.0,4.0,4.1,2.31,8.0
3,0.29,Premium,I,VS2,62.4,58.0,334.0,4.2,4.2,2.63,46.7
4,0.31,Good,J,SI2,63.3,58.0,335.0,4.3,4.3,2.75,51.9
5,0.24,Very Good,J,VVS2,62.8,57.0,3932.9,3.9,4.0,2.48,38.7
6,0.24,Very Good,I,VVS1,62.3,57.0,336.0,4.0,4.0,2.47,38.8
7,0.26,Very Good,H,SI1,61.9,55.0,337.0,4.1,4.1,2.53,42.3
8,0.22,Fair,E,VS2,65.1,61.0,337.0,3.9,3.8,2.49,36.4
9,0.23,Very Good,H,VS1,59.4,61.0,338.0,4.0,4.0,2.39,8.0
10,0.31,Good,J,SI2,63.3,58.0,335.0,4.3,4.3,2.75,51.9
11,0.3,Good,J,SI1,64.0,55.0,339.0,4.2,4.3,2.73,49.7
12,0.23,Ideal,J,VS1,62.8,56.0,340.0,3.9,3.9,2.46,37.7
13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.9,3.8,2.33,34.7
14,0.31,Ideal,J,SI2,62.2,54.0,344.0,4.3,4.4,2.71,51.5
15,'0.2',Premium,E,SI2,60.2,62.0,345.0,3.8,3.8,2.27,32.3
16,0.32,Premium,E,I1,60.9,58.0,345.0,4.4,4.4,2.68,51.9
17,0.3,Ideal,I,SI2,62.0,54.0,348.0,4.3,4.3,2.68,50.1
18,0.3,Good,J,SI1,63.4,54.0,351.0,4.2,4.3,2.7,49.0
19,0.3,Good,J,SI1,63.8,56.0,351.0,4.2,4.3,4,63.8
20,0.3,Very Good,J,SI1,62.7,59.0,351.0,4.2,4.3,2.66,47.8
21,0.3,Good,I,SI2,63.3,56.0,351.0,4.3,4.3,4,64.8
22,0.23,Very Good,E,VS2,63.8,55.0,352.0,3.9,3.9,2.48,37.4
23,0.23,Very Good,H,VS1,61.0,57.0,353.0,3.9,4.0,2.41,37.6
24,0.31,Very Good,J,SI1,59.4,62.0,353.0,4.4,4.4,2.62,8.0
25,0.3,Good,J,SI1,63.4,54.0,351.0,4.2,4.3,2.7,49.0
26,0.31,Very Good,J,SI1,58.1,62.0,353.0,4.4,4.5,2.59,8.0
27,0.23,Very Good,G,VVS2,60.4,58.0,354.0,4.0,4.0,2.41,38.4
28,0.24,Premium,I,VS1,62.5,57.0,355.0,4.0,3.9,2.47,38.6
29,0.3,Very Good,J,VS2,62.2,57.0,357.0,4.3,4.3,2.67,49.1
...,...,...,...,...,...,...,...,...,...,...,...
53913,0.57,Premium,E,IF,59.8,60.0,2753.0,5.4,5.4,3.23,8.0
53914,0.61,Premium,F,VVS1,61.8,59.0,2753.0,5.5,5.4,3.36,99.4
53915,0.8,Good,G,VS2,64.2,58.0,2753.0,5.8,5.8,3.74,126.9
53916,0.84,Good,I,VS1,63.7,59.0,2753.0,5.9,5.9,3.77,132.1
53917,0.77,Ideal,E,SI2,62.1,56.0,2753.0,5.8,5.9,3.63,124.2
53918,0.74,Good,D,SI1,63.1,59.0,2753.0,5.7,5.7,3.61,118.3
53919,0.9,Very Good,J,SI1,63.2,60.0,2753.0,6.1,6.1,3.86,143.9
53920,0.76,Premium,I,VS1,59.3,62.0,2753.0,5.9,5.8,3.49,8.0
53921,0.76,Ideal,I,VVS1,62.2,55.0,2753.0,5.9,5.9,3.66,126.5
53922,0.7,Very Good,E,VS2,62.4,60.0,2755.0,5.6,5.6,3.49,109.1
53923,0.7,Very Good,E,VS2,62.8,60.0,2755.0,5.6,5.7,3.53,111.5
53924,0.7,Very Good,D,VS1,63.1,59.0,2755.0,5.7,5.6,3.55,112.3
53925,0.73,Ideal,I,VS2,61.3,56.0,2756.0,5.8,5.8,3.57,120.9
53926,0.73,Ideal,I,VS2,61.6,55.0,2756.0,5.8,5.8,3.59,122.0
53927,0.79,Ideal,I,SI1,61.6,56.0,2756.0,6.0,6.0,3.67,130.4
53928,0.71,Ideal,E,SI1,61.9,56.0,2756.0,5.7,5.7,3.54,115.8
53929,0.79,Good,F,SI1,58.1,59.0,2756.0,6.1,6.1,3.54,8.0
53930,0.79,Premium,E,SI2,61.4,58.0,2756.0,6.0,6.0,3.68,132.3
53931,0.71,Ideal,G,VS1,61.4,56.0,2756.0,5.8,5.7,3.53,116.5
53932,0.71,Premium,E,SI1,60.5,55.0,2756.0,5.8,5.7,3.49,116.0
53933,0.71,Premium,F,SI1,59.8,62.0,2756.0,5.7,5.7,3.43,8.0
53934,0.7,Very Good,E,VS2,60.5,59.0,2757.0,5.7,5.8,3.47,114.1
53935,0.71,Premium,E,SI1,60.5,55.0,2756.0,5.8,5.7,3.49,116.0
53936,0.7,Very Good,E,VS2,61.2,59.0,2757.0,5.7,5.7,3.49,113.6
53937,0.72,Premium,D,SI1,62.7,59.0,2757.0,5.7,5.7,3.58,116.7
53938,0.72,Ideal,D,SI1,60.8,57.0,2757.0,5.8,5.8,3.5,115.9
53939,0.72,Good,D,SI1,63.1,55.0,2757.0,5.7,5.8,3.61,118.1
53940,0.7,Very Good,D,SI1,62.8,60.0,2757.0,5.7,5.7,3.56,114.4
53941,0.86,Premium,H,SI2,61.0,58.0,2757.0,6.2,6.1,3.74,140.8
53942,0.75,Ideal,D,SI2,62.2,55.0,2757.0,5.8,5.9,3.64,124.6

# 12. In diamonds data set Using the volume calculated above, create bins that have equal population within them. Generate a report that contains cross tab between bins and cut. Represent the number under each cell as a percentage of total.

In [19]:
bins = pd.qcut(df2['volume'], 10) #creating bins of equal population of 10
df2['bins'] = pd.DataFrame(bins)
df3=pd.crosstab(df2['bins'],df2['cut'],margins=False) #creating crosstab between bins and cut columns
totalSum = df3.sum() # total sum of all crosstab colums is found, for percent calculation
totalSum

cut
Fair          1610
Good          4907
Ideal        21551
Premium      13792
Very Good    12082
dtype: int64

In [20]:
df3 = df3.astype('float') #by default df3 takes datatype of int , hence type casted for percent calculation

def percent(row):
    colIndex = 0
    for col in df3.columns:
        row[col]=(row[col]/totalSum[colIndex])*100.0
        colIndex+=1;
        
df3.apply(lambda row : percent(row),axis=1)      # row by row percent is calculated for df2(crosstab) dataframe 

df3

cut                  Fair   Good   Ideal  Premium  Very Good
bins
(-0.001, 8.0]       260.0  914.0   493.0   2320.0     1652.0
(8.0, 51.22]         23.0  424.0  2288.0   1038.0     1377.0
(51.22, 59.282]      10.0  221.0  3342.0   1131.0      696.0
(59.282, 73.572]     37.0  383.0  2801.0   1226.0      940.0
(73.572, 92.849]    113.0  407.0  2879.0    944.0     1052.0
(92.849, 119.215]   221.0  464.0  2355.0   1003.0     1352.0
(119.215, 158.174]  390.0  738.0  1726.0   1118.0     1421.0
(158.174, 176.055]  177.0  604.0  1690.0   1540.0     1383.0
(176.055, 232.947]  136.0  268.0  2355.0   1614.0     1021.0
(232.947, 838.502]  243.0  484.0  1622.0   1858.0     1188.0